"""
Recommendation model — stores vacancy recommendations for users.
Generated by the AI matching engine with detailed score breakdown.
"""

from sqlalchemy import Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Recommendation(TimestampMixin, Base):
    __tablename__ = "recommendations"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    vacancy_id: Mapped[int] = mapped_column(
        ForeignKey("vacancies.id", ondelete="CASCADE"), index=True, nullable=False
    )

    # ── Score breakdown ────────────────────────────────────────────
    overall_score: Mapped[float] = mapped_column(Float, nullable=False)
    keyword_score: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    semantic_score: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # ── Explainability ────────────────────────────────────────────
    matched_skills: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON array
    missing_skills: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON array
    explanation: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Strategy metadata ─────────────────────────────────────────
    strategy: Mapped[str | None] = mapped_column(String(30), nullable=True)

    # ── Relations ──────────────────────────────────────────────────
    vacancy: Mapped["Vacancy"] = relationship(lazy="selectin")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<Recommendation(id={self.id}, user_id={self.user_id}, "
            f"score={self.overall_score}, strategy={self.strategy})>"
        )
