"""add advanced vacancy fields

Revision ID: 239807a93159
Revises: a4e476067f59
Create Date: 2026-04-17 12:55:33.672231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239807a93159'
down_revision: Union[str, None] = 'a4e476067f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('nice_to_have_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('industry_domain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tools_stack', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('languages_stack', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('human_languages', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('work_format', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_column('work_format')
        batch_op.drop_column('human_languages')
        batch_op.drop_column('languages_stack')
        batch_op.drop_column('tools_stack')
        batch_op.drop_column('industry_domain')
        batch_op.drop_column('nice_to_have_skills')
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###
